=== tautologistics/CDub.LogicEngine/src/CDub.LogicEngine/CDub.LogicEngine.Test.Console/Ruleset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by default user (Barnes&Noble.com) -->
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="opType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="eq"/>
			<xs:enumeration value="lt"/>
			<xs:enumeration value="gt"/>
			<xs:enumeration value="ct"/>
			<xs:enumeration value="sw"/>
			<xs:enumeration value="ew"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="sourceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="static"/>
			<xs:enumeration value="input"/>
			<xs:enumeration value="output"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="clauseType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="and"/>
			<xs:enumeration value="or"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="rulesetBase">
		<xs:sequence>
			<xs:element name="testinput" type="testdataBase" minOccurs="0"/>
			<xs:element name="testoutput" type="testdataBase" minOccurs="0"/>
			<xs:element ref="rule" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ruleBase">
		<xs:sequence>
			<xs:element ref="conditions" minOccurs="0"/>
			<xs:element name="success" type="actionsBase" minOccurs="0"/>
			<xs:element name="failure" type="actionsBase" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:anySimpleType" use="optional"/>
	</xs:complexType>
	<xs:complexType name="conditionsBase">
		<xs:sequence maxOccurs="unbounded">
			<xs:group ref="conditionGroup"/>
		</xs:sequence>
		<xs:attribute name="not" type="xs:boolean" use="optional"/>
		<xs:attribute name="op" type="clauseType" use="optional"/>
	</xs:complexType>
	<xs:complexType name="conditionBase">
		<xs:all>
			<xs:element name="input">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="source" type="sourceType"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="control">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:anySimpleType">
							<xs:attribute name="source" type="sourceType" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="not" type="xs:boolean" use="optional"/>
		<xs:attribute name="op" type="opType" use="required"/>
	</xs:complexType>
	<xs:complexType name="actionsBase">
		<xs:sequence>
			<xs:group ref="actionGroup" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="outputBase">
		<xs:sequence>
			<xs:element name="key" type="xs:string"/>
			<xs:element name="value">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:anySimpleType">
							<xs:attribute name="source" type="sourceType" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:group name="conditionGroup">
		<xs:choice>
			<xs:element ref="condition"/>
			<xs:element ref="conditions"/>
		</xs:choice>
	</xs:group>
	<xs:group name="actionGroup">
		<xs:choice>
			<xs:element ref="rule"/>
			<xs:element ref="output"/>
		</xs:choice>
	</xs:group>
	<xs:element name="ruleset" type="rulesetBase"/>
	<xs:element name="rule">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ruleBase"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="condition" type="conditionBase"/>
	<xs:element name="conditions" type="conditionsBase"/>
	<xs:element name="actions" type="actionsBase"/>
	<xs:element name="output" type="outputBase"/>
	<xs:complexType name="NVPair">
		<xs:sequence>
			<xs:element name="key" type="xs:string"/>
			<xs:element name="value" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="testdataBase">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="entry" type="NVPair"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== tautologistics/CDub.LogicEngine/src/CDub.LogicEngine/CDub.LogicEngine/Design/ruletest01.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="Ruleset.xsl"?><ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ruleset.xsd">  <testinput>    <entry>      <key>test.eq.alpha</key>      <value>abc</value>    </entry>    <entry>      <key>test.eq.num</key>      <value>123</value>    </entry>    <entry>      <key>test.sw</key>      <value>abc</value>    </entry>    <entry>      <key>test.ew</key>      <value>abc</value>    </entry>    <entry>      <key>test.ct</key>      <value>abc</value>    </entry>    <entry>      <key>test.lt.alpha</key>      <value>abc</value>    </entry>    <entry>      <key>test.lt.num</key>      <value>123</value>    </entry>    <entry>      <key>test.gt.alpha</key>      <value>abc</value>    </entry>    <entry>      <key>test.gt.num</key>      <value>123</value>    </entry>    <entry>      <key>test.source</key>      <value>abc</value>    </entry>    <entry>      <key>test.actionsource</key>      <value>xxx</value>    </entry>  </testinput>  <testoutput>    <entry>      <key>test.ct.pass</key>      <value>OK</value>    </entry>    <entry>      <key>test.eq.alpha.fail</key>      <value>OK</value>    </entry>    <entry>      <key>test.gt.alpha.pass</key>      <value>OK</value>    </entry>    <entry>      <key>test.gt.num.pass</key>      <value>OK</value>    </entry>    <entry>      <key>test.gt.num.fail</key>      <value>OK</value>    </entry>    <entry>      <key>test.sw.fail</key>      <value>OK</value>    </entry>    <entry>      <key>test.lt.num.pass</key>      <value>OK</value>    </entry>    <entry>      <key>test.ew.fail</key>      <value>OK</value>    </entry>    <entry>      <key>test.eq.num.fail</key>      <value>OK</value>    </entry>    <entry>      <key>test.actionsource.output</key>      <value>OK</value>    </entry>    <entry>      <key>test.source.static_static</key>      <value>OK</value>    </entry>    <entry>      <key>test.ct.fail</key>      <value>OK</value>    </entry>    <entry>      <key>test.actionsource.input</key>      <value>OK</value>    </entry>    <entry>      <key>actionsource.output</key>      <value>xxx</value>    </entry>    <entry>      <key>test.lt.alpha.fail</key>      <value>OK</value>    </entry>    <entry>      <key>test.source.static_output</key>      <value>OK</value>    </entry>    <entry>      <key>test.sw.pass</key>      <value>OK</value>    </entry>    <entry>      <key>test.lt.num.fail</key>      <value>OK</value>    </entry>    <entry>      <key>actionsource.static</key>      <value>xxx</value>    </entry>    <entry>      <key>test.source.input_static</key>      <value>OK</value>    </entry>    <entry>      <key>test.gt.alpha.fail</key>      <value>OK</value>    </entry>    <entry>      <key>test.source.output_static</key>      <value>OK</value>    </entry>    <entry>      <key>test.eq.num.pass</key>      <value>OK</value>    </entry>    <entry>      <key>actionsource.input</key>      <value>xxx</value>    </entry>    <entry>      <key>test.source.output</key>      <value>xxx</value>    </entry>    <entry>      <key>test.source.static_input</key>      <value>OK</value>    </entry>    <entry>      <key>test.actionsource.static</key>      <value>OK</value>    </entry>    <entry>      <key>test.lt.alpha.pass</key>      <value>OK</value>    </entry>    <entry>      <key>test.ew.pass</key>      <value>OK</value>    </entry>    <entry>      <key>test.eq.alpha.pass</key>      <value>OK</value>    </entry>    <entry>      <key>test.not.condition.pass</key>      <value>OK</value>    </entry>    <entry>      <key>test.not.condition.fail</key>      <value>OK</value>    </entry>    <entry>      <key>test.not.clause.pass</key>      <value>OK</value>    </entry>    <entry>      <key>test.not.clause.fail</key>      <value>OK</value>    </entry>    <entry>      <key>test.clause.and.pass</key>      <value>OK</value>    </entry>    <entry>      <key>test.clause.and.fail</key>      <value>OK</value>    </entry>    <entry>      <key>test.clause.or.pass</key>      <value>OK</value>    </entry>    <entry>      <key>test.clause.or.fail</key>      <value>OK</value>    </entry>    <entry>      <key>test.nested.or_and.pass</key>      <value>OK</value>    </entry>    <entry>      <key>test.nested.or_and.fail</key>      <value>OK</value>    </entry>    <entry>      <key>test.nested.and_or.pass</key>      <value>OK</value>    </entry>    <entry>      <key>test.nested.and_or.fail</key>      <value>OK</value>    </entry>    <entry>      <key>test.nested.rule.outer.pass</key>      <value>OK</value>    </entry>    <entry>      <key>test.nested.rule.inner.pass</key>      <value>OK</value>    </entry>    <entry>      <key>test.nested.rule.outer.fail</key>      <value>OK</value>    </entry>    <entry>      <key>test.nested.rule.inner.fail</key>      <value>OK</value>    </entry>
